## Este playbook realiza la configuracion inicial descrita en el fichero txt Video 1 - Configuracion inicial de nodos.

---
- hosts: "{{ hostsgroup }}"
  gather_facts: no
  
  tasks:
    - name: Creacion usuario ansible.
      user:
        name: ansible
        state: present
        password_lock: yes
        uid: 10001
        comment: "Ansible user."
    - name: Modificacion sudoers.
      template:
        src: /etc/ansible/templates/sudoers.j2
        dest: /etc/sudoers.d/ansible
        mode: 0440
    - name: Copia clave SSH usuario ansible.  
      authorized_key:
        user: ansible
        state: present
        manage_dir: yes
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
    - name: Obtener configuracion de red del nodo.
      setup:
        gather_subset: network
    - name: Configuracion del archivo /etc/hosts del nodo.
      lineinfile:
        backup: yes
        path: /etc/hosts
        state: present
        line: "{{ hostvars[inventory_hostname]['ansible_' + item]['ipv4']['address'] }} {{ inventory_hostname }}"
      when: ( hostvars[inventory_hostname]['ansible_' + item]['active'] == true and hostvars[inventory_hostname]['ansible_' + item]['ipv4'] is defined and hostvars[inventory_hostname]['ansible_' + item]['ipv4']['network'] == network_service )
      with_items:
        - "{{ hostvars[inventory_hostname]['ansible_interfaces'] }}"

...
